### ISSUE TITLE
Predict with custom config fails.

### ISSUE THREAD

**Issue by smarzban** [tryolabs/luminoth#105]
Fix is simple. Config files need to be loaded and merged with base_config before all the processing!

**Comment by IanTayler** [comment]
Hi, @smarzban !
Thanks for the heads up! @gastonrod07 will be working on it. Would you mind posting your stack trace/error message so that we know exactly what the problem is? Are you by any chance getting `AttributeError` when trying to access `config.train.job_dir` or `config.train.run_name`?

Thanks in advance!

**Comment by gastonrod07** [comment]
Hi, thanks for your comments. I hope that the fix in the PR #106 could resolve this issue. 
Please take a look and if it's still not working, let me know!

**Comment by smarzban** [comment]
this works! thanks so much 👍
