### ISSUE TITLE
Duration of default Google Cloud ML training job with voc2012

### ISSUE THREAD

**Issue by clicit** [tryolabs/luminoth#111]
I used luminoth (checked out from GIT) with default settings, voc2012 (transformed and uploaded to a bucket) and the sample_config.yml (?)

A general question:
How long should the job approximately take? Because I got it running - but now it's running for over 35h and still didn't complete..!?

thanks!

**Comment by IanTayler** [comment]
Hi @clicit !

By default we train for 1000 epochs (i.e. until all images in the dataset have been used for training at least 1000 times). On a cluster with tier `BASIC_GPU` (which is the default) that should take around 1000 hours.

That said, 1000 epochs absolutely overkill. Training times for VOC2012 reported in papers range from 80k steps (i.e. around 10 epochs, which you should have passed by now) to 135 epochs (which would take you five to six days on a `BASIC_GPU` cluster). Consider it a placeholder for now, it will be fine tuned in the future.

You can stop the job at any time and you won't lose your progress. You can also monitor your job through the logs in CloudML, by using tensorboard, or by running an evaluation job (run `lumi cloud gc evaluate --help`. Although the PR adding gcloud evaluation was merged yesterday, so that option may not be available in your version of luminoth).

We will soon upload FasterRCNN checkpoints pretrained on Pascal VOC so that you can get predictions out of the box. We're fine-tuning the hyperparameters to get the best results, first.

In the meantime, if you have any other questions or comments, don't be afraid to ask!

**Comment by clicit** [comment]
Great thank you!

I will checkout and use the new version to run an evaluation job.

If you would have some useful hints for the tensorboard usage it would be 
great!

**Comment by clicit** [comment]
Short feedback to the` lumi cloud gc evaluate` implementation:
On Windows  `tf.gfile.ListDirectory(package_dir) ` doesn’t work (probably because `gs://` is not supported - same problem than with tensorboard ?)

**Comment by IanTayler** [comment]
Thanks, @clicit!

We'll take it into consideration.
