### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by ChromoBacterium** [tryolabs/luminoth#148]
Hi there! The OS I am working with is Windows 10. I think I installed Luminoth successfully in the command prompt. When I typed lumi --help however, I got this: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'lumi' is not defined

I am using Python 3.5 with Tensorflow installed. I do not think this should be a problem. Can I get help with the installation?

**Comment by ChromoBacterium** [comment]
P.S. I am specifically running Windows 10 Home. OS version is 1709, build number 16299.125.

**Comment by dekked** [comment]
Hi @ChromoBacterium!

This might be because the "lumi" command is not set in your environment's PATH. You can [check this out](https://www.computerhope.com/issues/ch000549.htm) for info on how to change your PATH variable.

I am sorry that we can't provide more help, since none of us have Windows machine to try this. Thus, Luminoth is not officially supported in Windows :(

See https://github.com/tryolabs/luminoth/issues/146.

**Comment by dekked** [comment]
On a second look (seeing your traceback), it looks like you might be running `lumi --help` in a Python interactive shell instead of the bash shell.

**Comment by JustusWest** [comment]
Was this ever resolved? I am having a similar issue when trying to run `lumi --help`

I get the message : `'lumi' is not recognized as an internal or external command,
operable program or batch file.`

On `pip install luminoth` it says: ` luminoth in c:\users\username\appdata\roaming\python\python36\site-packages (0.2.3)`

I have my path variable set to that but `lumi --help` still does not work. I would love to use this library for my research project, but would like to avoid using Google Cloud because I have access to a sufficiently powerful Windows machine.

**Comment by ChromoBacterium** [comment]
Yes, it was resolved in a way. You may want to re-install it (as it worked with me). However, it will still not work because one of the libraries - DeepMind Sonnet - does not currently support Windows (at least not the binary wheel packages). I found the library to work on Google Colaboratory , which already runs Linux and comes with a free GPU. If you don't have any problems using Google Colab, I suggest using it until Windows support for Sonnet comes out. Until then, you may want to try compiling the source code (for Sonnet) from source (I recommend using Git Bash to run any shell files that may be in the file, it works for me). I hope this helped!
