### ISSUE TITLE
Problems about Faster R-CNN

### ISSUE THREAD

**Issue by xiaohu2015** [tryolabs/luminoth#155]
I found that Faster R-CNN does not support batch training, only can feed one image

**Comment by vierja** [comment]
Hi @xiaohu2015!

Batch training is not required for Faster R-CNN (it is not used in the original paper) and it makes it harder to train on "regular" GPUs because of memory constrains. We are currently working on an SSD implementation which will support batch training.

We are open to contributions, so feel free to open a pull request implementing batch support, we are definitely interested and are willing to help in any way we can.

Thanks.

**Comment by xiaohu2015** [comment]
Thanks a lot. I got it.
