### ISSUE TITLE
How to fine-tune from a provided checkpoint ?

### ISSUE THREAD

**Issue by calledbymountains** [tryolabs/luminoth#187]
I would like to fine tune the provided pretrained model for Faster-RCNN trained on MSCOCO on some other dataset.

How can I do this fine-tuning ? To the best of my knowledge there is no such documentation on this aspect.

**Comment by joaqo** [comment]
Hi! You'll need to do the following to fine-tune on other datasets:
- If your dataset is not one of the supported datasets (COCO, PASCAL, OpenImages) you'll need to create a custom data reader for you data. Take a look at the [PASCAL reader](https://github.com/tryolabs/luminoth/blob/master/luminoth/tools/dataset/readers/object_detection/pascalvoc.py) for an example of how to do it. Then you'll need to convert your data to a TF Recordd using this data reader.
- You'll need to create a custom config file which should point to the pretrained model's folder, so training resumes from its checkpoint.

Cheers!

**Comment by mauricio-meli** [comment]
When you say 

> point to the pretrained model's folder

you mean the job_dir in the train section right? Should it work with lumi cloud gc? When I try to retrain the model pointing to the old job_dir, a new job with a different config.yml is created in google cloud. It downloads the resnet_v1_101.ckpt checkpoint instead of using my previously trained checkpoint.

**Comment by giuliafonts** [comment]
@mauricio-meli did you find a solution?
