### ISSUE TITLE
Evaluate function in Google Cloud

### ISSUE THREAD

**Issue by shreyjasani** [tryolabs/luminoth#204]
I'm using Windows and Google Cloud. I'm getting the following error when using evaluate on my running job:

![capture](https://user-images.githubusercontent.com/16943768/44130377-34186d32-a01b-11e8-8587-b19dea7c521b.PNG)

**Comment by dekked** [comment]
Hello @shreyjasani!

Can you list the contents of the bucket? And in particular, the `packages` folder.

If the training run, there must be a packet somewhere. Maybe like `package_files = tf.gfile.ListDirectory(train_packages_dir)` in `gcloud.py` is not returning what we expect, for some reason?

**Comment by shreyjasani** [comment]
Bucket contents of the training job:

![capture](https://user-images.githubusercontent.com/16943768/44154340-815f7d94-a078-11e8-999b-fdbef8d1c86e.PNG)

And specifically, the packages folder:
![capture](https://user-images.githubusercontent.com/16943768/44155228-bdea07be-a07a-11e8-9027-243954e1e213.PNG)

So I'm seeing the tar.gz file in `packages` so it might just be the `packages_files` line

**Comment by dekked** [comment]
Can you put a breakpoint before that line (`pdb` or `ipdb`) and see what's going on?

Given the content in the directory, it really looks like it shouldn't fail, unless `tf.gfile.ListDirectory` is returning empty for some reason in Windows.

**Comment by dekked** [comment]
Forgot to say... a workaround would be to run `eval` with `--rebuild` option.

But it would be nice to get this fixed in case it's an easy to fix bug :)

**Comment by dekked** [comment]
The .tar.gz is the package that contains Luminoth's source code, the same thing you see in GitHub here. It is needed by ML Engine, since all the dependencies that it installs for running your code/model must be encapsulated in a package.

The checkpoint is that is stored in the job's directory (in this case, bucket). This does have the `metadata.json` file you are describing.

I am still wondering why this failed without `--rebuild`, though. Don't know if `ListDirectory` is not returning what we expect, but anyway, when we do implement #208 we should clean up the CLI a bit and avoid this case altogether.
