### ISSUE TITLE
Instant feedback for --help commands.

### ISSUE THREAD

**Issue by vierja** [tryolabs/luminoth#5]
Currently, when running a simple `lumi --help` command it takes more than 7s for the message to appear. This is because of all the loading of models/sonnet/etc.

We should change the way we import/load submodules to have an instant reply.

**Comment by IanTayler** [comment]
This is an issue with tensorflow in python 3. `lumi --help` takes ~1s in python 2.7

Solving the issue on our side implies measures that are too drastic for a problem that is probably temporary. We should consider reopening this issue only if it isn't fixed in the tensorflow repo after some time.

I'm closing the issue. For more information, see the discussion in the tensorflow repo
- [Faster to import tensorflow.contrib on Python 3](https://github.com/tensorflow/tensorflow/pull/11830)
- [import tensorpack on python 3.6 too slow](https://github.com/ppwwyyxx/tensorpack/issues/363)
- [Make 'import tensorflow' go faster](https://github.com/tensorflow/tensorflow/pull/11919) (merged)

**Comment by vierja** [comment]
https://github.com/tensorflow/tensorflow/pull/11830 was merged. Let's hope it makes it to a 1.3.1 release. 🥇
